--- 
apiVersion: batch/v1beta1
kind: CronJob
metadata: 
  name: helloworld-cron
spec: 
  failedJobsHistoryLimit: 2
  jobTemplate: 
    spec: 
      template: 
        spec: 
          containers: 
            - 
              command: 
                - echo
                - kube_+++++++
              image: nginx
              name: nginx
          restartPolicy: Never
  schedule: "* * * * *"
  successfulJobsHistoryLimit: 1
