---

apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: helloworld-cron
spec:
  schedule: "* * * * *"
  successfulJobsHistoryLimit: 3
  failedJobsHistoryLimit: 2
  jobTemplate:
	spec:
	 template:
	  spec:
	   containers:
	   - name: nginx
             image: nginx
             command: ["echo", "kube_+++++++"]
	   restartPolicy: Never
