apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: helloworld-cron
spec:
  schedule: "* * * * *"
  successfulJobsHistoryLimit: 2
  failedJobsHistoryLimit: 5
  jobTemplate:
        spec:
         template:
          spec:
           containers:
           - name: nginx
             image: nginx
             command: ["sh", "/mnasd"]
           restartPolicy: Never
