apiVersion: batch/v1
kind: Job
metadata:
  name: helloworld
spec:
  completions: 10
  parallelism: 2
  template:
    spec:
      containers:
      - name: nginx
        image: nginx
        command: ["echo", "KUBEEE"]
      restartPolicy: Never
