apiVersion: v1
kind: Pod
metadata:
  name: mypod
spec:
  containers:
  - name: mypod
    image: busybox
    volumeMounts:
    - name: foo
      mountPath: "/etc/my.cnf"
      readOnly: true
  volumes:
  - name: foo
    configMap:
      name: mysql
