apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: nginx
  name: nginx
spec:
  replicas: 8
  selector:
    matchLabels:
      app: nginx
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: nginx
    spec:
      volumes:
      - name: task-pv
        persistentVolumeClaim:
         claimName: my-pvc
      containers:
      - image: nginx
        name: nginx
        volumeMounts:
         - mountPath: "/usr/share/nginx/html"
           name: task-pv
