apiVersion: v1
kind: PersistentVolume
metadata:
  name: mypv
spec:
  storageClassName: hostpath
  persistentVolumeReclaimPolicy: Recycle
  capacity:
    storage: 20Mi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/nfs/client"
