apiVersion: v1
kind: PersistentVolume
metadata:
  name: mypv2
  labels: 
    volume: hdd
spec:
  storageClassName: hostpath
  capacity:
    storage: 20Mi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/nfs/client"
