apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: my-pvc1
spec:
  storageClassName: hostpath
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 15Mi
  selector:
    matchLabels:
      volume: hdd
