apiVersion: v1
kind: Deployment
metadata:
  name: goproxy
  labels:
    app: goproxy
spec:
 replicas: 3 
 selectors:
  matchlabels:
    app: goproxy
 
  containers:
  - name: goproxy
    image: nginx
    ports:
    - containerPort: 80
    readinessProbe:
      tcpSocket:
        port: 8080
      initialDelaySeconds: 5
      periodSeconds: 10
    livenessProbe:
      tcpSocket:
        port: 8080
      initialDelaySeconds: 15
      periodSeconds: 20
